### PR TITLE
Also setting the timeout on connect, to avoid hanging forever

### PR DESCRIPTION
**Pull request by Lucas-C**
Without this fix, the CLI hangs forever when trying to reach a closed server.

I'm waiting for my friend server to be back UP for a final test, but tell me if this looks good to you !

### CODE REVIEW

**Comment by Lucas-C** [comment]
Test successful !

**Comment by thbaumbach** [comment]
Thanks for your help, I will look into the PR ASAP

**Comment by thbaumbach** [comment]
lgtm

**Comment by Lucas-C** [comment]
Thanks for merging it !

**Pull request merged**
